FROM opensuse/leap:15.6

RUN zypper refresh && \
    zypper install -y nginx && \
    zypper clean --all

RUN mkdir -p /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html

COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
